# Generated by Django 5.0 on 2023-12-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoformula', '0002_alter_course_options_course_photo_instructor_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
